urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('youtube/callback/', views.OAuthCallBack.as_view(), name='oauth_callback'),
    path('dashboard/<slug:slug>/youtube/connect/', views.YouTubeConnect.as_view(), name='youtube_connect'),
    path('dashboard/<slug:slug>/youtube/channels/', views.YouTubeChannelList.as_view(), name='youtube_channels'),
    path('dashboard/<slug:slug>/youtube/channels/set/', views.YouTubeChannelSet.as_view(), name='youtube_channels_set'),

    # confirm name, basic info for podcast
    path('dashboard/<slug:slug>/tube/setup/', views.VideoSyncSetupPodcastPage.as_view(), name='videosync_setup_podcast_page'),
    path('dashboard/<slug:slug>/tube/edit/', views.VideoSyncPodcastUpdatePage.as_view(), name='videosync_podcast_update_page'),

    path('dashboard/<slug:slug>/tube/episodes/', views.VideoSyncEpisodeListPage.as_view(), name='videosync_episode_list_page'),
    path('dashboard/<slug:podcast_slug>/tube/episodes/new/', views.VideoSyncEpisodeCreatePage.as_view(), name='videosync_episode_create_page'),
    path('dashboard/<slug:podcast_slug>/tube/episodes/<int:pk>/', views.VideoSyncEpisodeTemplatesPage.as_view(), name='videosync_episode_templates_page'),
    path('dashboard/<slug:podcast_slug>/tube/episodes/<int:pk>/edit/', views.VideoSyncEpisodeUpdatePage.as_view(),
    name='videosync_episode_update_page'),
    path('dashboard/<slug:podcast_slug>/tube/episodes/<int:pk>/tube/upload/', views.VideoSyncEpisodeUpload.as_view(),
    name='videosync_episode_upload'),

    path('image-proxy/', views.ImageProxy.as_view(), name='image_proxy'),
    path('api/youtube/upload/', views.YouTubeUploadApi.as_view(), name='youtube_upload_api'),
    path('api/video/', views.VideoSyncEpisodeCreateVideoApi.as_view(), name='video_create_api'),
    path('api/podcast/<int:podcast_id>/blur-image/', views.ImageProcessApi.as_view(), name='blur_image_api'),
]

models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.urls import reverse
from s3direct.fields import S3DirectField
from colorfield.fields import ColorField

from dashboard.helper_slug import make_slug
from dashboard.models import Podcast, Episode

from redwoodlabs.helpers import generate_random_id

class YouTubeAccount(models.Model):
    email = models.EmailField(max_length=128, unique=True)
    youtube_id = models.CharField(max_length=128, unique=True)
    access_token = models.CharField(max_length=256, null=True, blank=True)
    refresh_token = models.CharField(max_length=256, null=True, blank=True)

class VideoSyncPodcast(models.Model):

    id = models.BigIntegerField(default=generate_random_id, primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128, unique=True)

    image_path = S3DirectField(dest='images', null=True, blank=True,
        verbose_name='Podcast Artwork',
        help_text='The cover image that shows on Apple Podcasts, etc...')
    primary_color = ColorField(null=True, blank=True,
        help_text='Highlight color in images. Example: #333333')
    secondary_color = ColorField(null=True, blank=True, default='#FFFFFF',
        help_text='Alternative color in images. Example: #FFFFFF')
    logo_path = S3DirectField(dest='images', null=True, blank=True,
        verbose_name='Podcast Logo',
        help_text='Optional, but can be used for artwork.')
    font_name = models.CharField(max_length=200, null=True, blank=True,
        verbose_name='Font',
        help_text='Enter the name of any font from fonts.google.com.')

    default_template = models.CharField(max_length=100, null=True, blank=True,
        help_text='This is the default template used for new episodes')

    youtube_account = models.ForeignKey(YouTubeAccount, on_delete=models.SET_NULL, null=True, blank=True)
    youtube_channel_id = models.CharField(max_length=100, null=True, blank=True)
    youtube_channel_name = models.CharField(max_length=100, null=True, blank=True)

    blur_image_path = models.URLField(max_length=500, null=True, blank=True)

    related_podcast_object = models.OneToOneField(Podcast, on_delete=models.CASCADE, null=True, blank=True)

    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = make_slug(self)
        super().save(*args, **kwargs)

    def get_episodes(self):
        return self.videosyncepisode_set.all()

    def get_absolute_url(self):
        return reverse('videosync_episode_list_page', kwargs={'slug':self.slug})

    def get_edit_url(self):
        return reverse('videosync_podcast_update_page', kwargs={'slug':self.slug})

    @property
    def custom_font(self):
        font = None
        if self.font_name:
            font = {'param': self.font_name.replace(' ', '+'),'name': self.font_name }
        return font

    @property
    def youtube_connected(self):
        if self.youtube_account:
            return (self.youtube_account.access_token and self.youtube_account.refresh_token)
        return False

    @property
    def youtube_access_token(self):
        if self.youtube_account:
            return self.youtube_account.access_token
        return None

    @property
    def youtube_refresh_token(self):
        if self.youtube_account:
            return self.youtube_account.refresh_token
        return None


class VideoSyncEpisode(models.Model):

    IN_PROGRESS = 'P'
    SUCCESS = 'S'
    FAILED = 'F'
    UPLOAD_STATUS_CHOICES = (
        (IN_PROGRESS, 'In Progress'),
        (SUCCESS, 'Success'),
        (FAILED, 'Failed'),
    )

    id = models.BigIntegerField(default=generate_random_id, primary_key=True)
    podcast = models.ForeignKey(VideoSyncPodcast, on_delete=models.CASCADE)

    text = models.CharField(max_length=250, null=True, blank=True)
    season = models.IntegerField(null=True, blank=True,
        verbose_name='Season Number',
        help_text='Leave blank if your podcast does not have seasons')
    number = models.IntegerField(null=True, blank=True,
        verbose_name='Episode Number')
    image_path = S3DirectField(dest='images', null=True, blank=True,
        verbose_name='Episode Image',
        help_text='Photo of guest, or drawing, or other graphic')

    template = models.CharField(max_length=100, null=True, blank=True)

    related_episode_object = models.OneToOneField(Episode, on_delete=models.CASCADE, null=True, blank=True)

    artwork_path = models.URLField(max_length=500, null=True, blank=True)
    audio_path = models.URLField(max_length=500, null=True, blank=True)
    preview_path = models.URLField(max_length=500, null=True, blank=True)
    video_path = models.URLField(max_length=500, null=True, blank=True)

    upload_status = models.CharField(max_length=1, choices=UPLOAD_STATUS_CHOICES, null=True, blank=True)
    sync_status = JSONField(blank=True, null=True)
    youtube_id = models.CharField(max_length=500, null=True, blank=True)

    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-related_episode_object__published']

    def get_absolute_url(self):
        return reverse('videosync_episode_templates_page', kwargs={'podcast_slug':self.podcast.slug, 'pk': self.pk})

    def get_edit_url(self):
        return reverse('videosync_episode_update_page', kwargs={'podcast_slug':self.podcast.slug, 'pk': self.pk})

    @property
    def image(self):
        if self.image_path:
            return self.image_path
        else:
            return 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1502&q=80'

    @property
    def video_location(self):
        path = os.path.join('media', str(self.podcast.related_podcast_object.user.pk), str(self.podcast.related_podcast_object.pk), str(self.related_episode_object.id) + '.mp4')
        if os.path.exists(path):
            return path
        return None


    @property
    def youtube_url(self):
        if self.youtube_id:
            return "https://www.youtube.com/watch?v=" + self.youtube_id
        return None

    @property
    def youtube_embed_url(self):
        if self.youtube_id:
            return "https://www.youtube.com/embed/" + self.youtube_id
        return None

    @property
    def card_graphic(self):
        if self.youtube_embed_url:
            return '<div class="embed-container"><iframe src="%s" frameborder="0" allowfullscreen></iframe></div>' % self.youtube_embed_url
        elif self.artwork_path:
            return '<img src="%s">' % self.artwork_path
        return None

    def update_sync_status(self, event):
        sync_status = []
        if self.sync_status:
            self.sync_status.append(event)
            sync_status = self.sync_status
        else:
            sync_status = [event]

        self.sync_status = sync_status
        self.save()

templates/videosync/_template.html
<div class="podart {% if wide %}podart-wide{% endif %} template-{{forloop.counter0}}" style="overflow: hidden;">
    <div class="podart--branding">Synced with <strong>{{STRINGS.site_name}}</strong></div>
    {% if template.image %}
        <div class="podart--episode-image" id="podartImage" {{template.image.style_tag|safe}}>
            <!-- <img src="{{episode.podcast.image_path}}" style="width:100%;height:auto;" /> -->
        </div>
    {% endif %}
    {% if template.logo and podcast.logo_path %}
        <img class="podart--show-logo" src="/image-proxy/?url={{template.logo.src}}" {{template.logo.style_tag|safe}}>
    {% endif %}
    {% if template.second_cover and podcast.image_path %}
        <img class="podart--show-logo" src="/image-proxy/?url={{template.second_cover.src}}" {{template.second_cover.style_tag|safe}}>
    {% endif %}
    <div class="podart--text-container" {{template.text_container.style_tag|safe}}>
        {% if template.podcast_name and podcast.name %}
            <div class="podart--podcast-name" {{template.podcast_name.style_tag|safe}}>{{podcast.name}}</div>
        {% endif %}
        {% if template.episode_number and episode.number %}
            <div class="podart--episode-number" {{template.episode_number.style_tag|safe}}>
                <span class="label" {{template.episode_number_label.style_tag|safe}}>Episode </span>{{episode.number}}
            </div>
        {% endif %}
        {% if template.episode_text %}
            <div class="podart--episode-text" {{template.episode_text.style_tag|safe}}>{{episode.text}}</div>
        {% endif %}
    </div>
    {% if template.mask %}
        <div class="podart--mask" {{template.mask.style_tag|safe}}></div>
    {% endif %}
</div>

{% if not hide_refine %}
    <div class="text-center"><a href="?t={{forloop.parentloop.counter0}}-{{forloop.counter0}}">Refine this template</a></div>
{% endif %}

templates/videosync/_template_styles.html
{% if podcast.custom_font %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family={{podcast.custom_font.param}}:400,600,700,800">
{% endif %}

<style type="text/css">
    .podart {
        border: 1px solid #efefef;
        width: 100%;
        padding-top: 56.25%;
        position: relative;
        font-size: 150%;
        line-height: 1.3;
        background: black;
        {% if podcast.font_name %}font-family: '{{podcast.custom_font.name}}', sans-serif;{% endif %}
    }
    .podart>* {
        position: absolute;
        z-index: 1;
    }
    .podart--branding {
        top: 0;
        right: 0;
        z-index: 1000;
        font-size: 40%;
        background: rgba(0,0,0,.6);
        color: white;
        text-transform: uppercase;
        font-family: 'DM Sans', 'Roboto', sans-serif;
        padding: 0.7%;
        line-height: 1;
        border-radius: 0 0 0 5px;
    }
    .podart .podart--mask,
    .podart .podart--text-container,
    .podart .podart--episode-image {
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
    }
    .podart .podart--mask {
        position: absolute;
        width: 100%;
        height: 100%;
        z-index: 2;
    }
    .podart .podart--text-container {
        z-index: 4;
    }
    .podart .podart--text-container * {
        color: inherit;
    }
    .podart .podart--episode-image {
        width: 100%;
        height: 100%;
        z-index: 0;
        background-position: center center;
        background-repeat: no-repeat;
        background-size: cover;
    }
    .podart .podart--show-logo {
        max-width: 100%;
        z-index: 3;
        max-height: 25%;
    }

</style>

templates/videosync/videosync_channel_list_page.html
{% extends "dashboard/base_dashboard.html" %}
{% load static %}
{% load humanize %}
{% load bootstrap4 %}

{% block dashboard_section %}

        <!-- <div class="row">
            <div class="col-lg-12">
                <div class="card mb-3 mt-4">
                    {% if podcast.youtube_connected %}
                        <div class="card-body rounded">
                            Your videos are being synced with <strong>{{podcast.youtube_channel_name}}</strong>
                        </div>
                    {% else %}
                        <div class="card-body rounded no-border bg-red">
                            <p>
                                <strong>Setup required!</strong><br>
                                You need to let us know what YouTube channel you'd like us to sync videos to.
                            </p>
                            <a href="{% url 'youtube_connect' podcast.slug %}" class="btn btn-styled btn-circle btn-white c-red btn-icon-left"><i class="fa fa-youtube"></i>Connect YouTube</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div> -->


        {% for channel in object_list %}
            {% with snippet=channel.snippet %}
                <div class="card mb-3">
                    <div class="row">

                        <div class="col-lg-8">
                            <div class="card-body pl-3 py-3">
                                <h5 class="heading heading-6 strong-500">
                                    <a href="">{{snippet.title}}</a>
                                </h5>
                                <div>
                                    <form action="{% url 'youtube_channels_set' podcast.slug %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="channel_name" value="{{snippet.title}}" />
                                        <input type="hidden" name="channel_id" value="{{channel.id}}" />
                                        <button type="submit" class="btn btn-styled btn-circle btn-white c-red">Use this Channel</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="card-image">
                                <img src="{{snippet.thumbnails.default.url}}" alt="{{snippet.title}}" class="img-fluid rounded">
                            </div>
                        </div>
                    </div>
                </div>
            {% endwith %}
        {% endfor %}

{% endblock dashboard_section %}

templates/videosync/videosync_episode_templates_page.html
{% extends "theme/base.html" %}
{% load static %}
{% load humanize %}
{% load bootstrap4 %}

{% block styles %}{% include "videosync/_template_styles.html" %}{% endblock styles %}

{% block content %}

    <section class="slice-xs bg-base-4">
        <div class="container">
            <a href="{% url 'videosync_episode_list_page' podcast.slug %}" class="c-white">← Back to Episode List</a>
        </div>
    </section>

    <section class="slice slice-sm border-bottom">
        <div class="container">
            <div class="row my-4">
                <div class="col-md-4 bg-light border">
                    <div class="row my-4">
                        <div class="col-12">
                            <div class="row">
                                <div class="col-12 mb-3">
                                    <h2 class="heading heading-4">
                                        Podcast Settings
                                        <a href="{{podcast.get_edit_url}}?redirect={{request.get_full_path}}" class="btn btn-styled btn-base-1 btn-circle btn-outline btn-xs">Edit</a>
                                    </h2>
                                </div>
                                <div class="col-12 mb-3">
                                    <span class="heading heading-light heading-sm text-uppercase strong-300">Name: </span>
                                    {{podcast.name}}
                                </div>
                                <div class="col-4">
                                    <div class="heading heading-light heading-sm text-uppercase strong-300 mb-2">Artwork</div>
                                    <img src="{{podcast.image_path}}" class="w-100">
                                </div>
                                <div class="col-4">
                                    <div class="heading heading-light heading-sm text-uppercase strong-300 mb-2">Logo</div>
                                    <img src="{{podcast.logo_path}}" class="w-100">
                                </div>
                                <div class="col-4">
                                    <div class="heading heading-light heading-sm text-uppercase strong-300 mb-2">Colors</div>
                                    <div class="btn btn-styled btn-xs btn-block" style="background-color: {{podcast.primary_color}}; color: {{podcast.secondary_color}};">Primary</div>
                                    <div class="btn btn-styled btn-xs btn-block mt-2" style="background-color: {{podcast.secondary_color}}; color: {{podcast.primary_color}};">Secondary</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="row">
                                <div class="col-12 mt-5">
                                    <h2 class="heading heading-4">
                                        Episode Settings
                                        <a href="{{episode.get_edit_url}}?redirect={{request.get_full_path}}" class="btn btn-styled btn-base-1 btn-circle btn-outline btn-xs">Edit</a>
                                    </h2>
                                    {% if not episode.image_path %}
                                        <div class="alert alert-info">To show what the templates should look like, we have included a sample image. Click edit to add your own</div>
                                    {% endif %}
                                </div>
                                <div class="col-4">
                                    <div class="heading heading-light heading-sm text-uppercase strong-300 mb-2">Text</div>
                                    {{episode.text}}
                                </div>
                                <div class="col-4">
                                    <div class="heading heading-light heading-sm text-uppercase strong-300 mb-2">Number</div>
                                    {{episode.number}}
                                </div>
                                <div class="col-4">
                                    <div class="heading heading-light heading-sm text-uppercase strong-300 mb-2">Image</div>
                                    <img src="{{episode.image}}" class="w-100">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">



                    {% if saved_template %}
                        <div class="row">
                            <div class="col-lg-12">
                                <strong>Chosen Template</strong>
                                {% include "videosync/_template.html" with template=saved_template hide_refine=saved_template %}
                            </div>
                            <div class="col-lg-12 pt-5 pb-2">
                                <h2 class="heading heading-4">Choose a different template</h2>
                            </div>
                        </div>

                    {% endif %}


                    {% for theme in themes %}
                        <div class="row">
                            {% for template in theme %}
                                <div class="{% if target_template %}col-lg-12{% else %}col-lg-12{% endif %} mb-3" {% if target_template %}id="targetTemplate"{% endif %}>
                                    <div class="podart-container">
                                        {% include "videosync/_template.html" with hide_refine=target_template %}
                                    </div>
                                </div>
                            {% endfor %}
                            {% if target_template %}
                                <div class="col-lg-12">
                                    <p>Now, use the edit buttons above to tweak the colors, photos, logos, etc... until you're happy with it. Then hit save below to save your choice.</p>

                                    <form method="post" action="{{ action_url }}" class="form" id="templateForm">
                                        {% csrf_token %}
                                        {% bootstrap_form form %}
                                        <input type="hidden" name="image_data" id="imageData" />
                                        <button type="submit" class="btn btn-styled btn-base-1 btn-circle" id="submitBtn">{{form_button_label|default:"Save"}}</button>
                                        <a href="{{episode.get_absolute_url}}" class="btn btn-styled btn-link ">Back to templates</a>
                                    </form>
                                </div>

                            {% endif %}
                        </div>
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

{% block scripts %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/html2canvas@1.0.0-rc.5/dist/html2canvas.min.js"></script>
    {% if target_template %}
        <script>
            function grabTemplate(form){
                html2canvas($('#targetTemplate .podart-container')[0], {
                    scale: 2,
                    useCORS: true,
                }).then(function(canvas) {
                    var image_data = canvas.toDataURL();
                    $("#imageData").val(image_data);
                    $(form).unbind().submit();
                });
            }

            $(document).ready(function(){
                $("#templateForm").submit(function(e){
                    e.preventDefault();
                    if ($('#id_template').val().indexOf('2-') >= 0 && '{{ podcast.blur_image_path }}' === ''){
                        $.get("{% url 'blur_image_api' podcast.id %}").then((res) => {
                            document.getElementById('podartImage').style.backgroundImage = 'url(/image-proxy/?url=' + res.imageUrl + ')';
                            grabTemplate(this);
                        });
                    } else {
                        grabTemplate(this);
                    }
                });
            })
        </script>
    {% endif %}
{% endblock %}

{% block facebook_pixel %}{% endblock facebook_pixel %}

templates/videosync/videosync_upload_page.html
{% extends "dashboard/base_dashboard.html" %}
{% load static %}
{% load humanize %}
{% load bootstrap4 %}

{% block styles %}{% include "videosync/_template_styles.html" %}{% endblock styles %}

{% block dashboard_section %}

        <div class="row">

            <div class="col-lg-4">
                {% if object.youtube_id %}
                    <iframe id="ytplayer" type="text/html" width="640" height="360"
                        src="{{object.youtube_embed_url}}"
                        frameborder="0"></iframe>
                {% elif object.preview_path or object.artwork_path %}
                    <div class="row">
                        <div class="col-lg-12">
                            {% if object.preview_path %}
                                <h4>Preview</h4>
                                <video height="480" controls controlsList="nodownload">
                                    <source src="{{object.preview_path}}" type="video/mp4">
                                        Your browser does not support the video tag.
                                    </source>
                                </video>
                                <br />
                            {% else %}
                                <img src="{{object.artwork_path}}" style="width:100%;" />
                                <!-- <p>Preview video in progress, please come back in a while.</p> -->
                            {% endif %}
                        </div>
                    </div>
                {% elif object.youtube_id %}
                    <iframe id="ytplayer" type="text/html" width="640" height="360"
                        src="{{object.youtube_embed_url}}"
                        frameborder="0"></iframe>
                {% endif %}
            </div>

            <div class="col-lg-8">
                <div class="alert alert-danger" id="errorMessage" style='display:none'>Error occurred while processing your video...</div>
                <div class="card mb-3 mt-4">
                    <div class="card-body rounded">
                        <strong>{{object.text}}</strong>
                        {% if object.related_episode_object.summary %}
                            <p>{{object.related_episode_object.summary}}</p>
                        {% endif %}
                        {% csrf_token %}
                        <button id="uploadBtn" type="button" class="btn btn-primary">Start Upload</button>
                    </div>
                </div>
            </div>

        </div>

{% endblock dashboard_section %}

{% block scripts %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/html2canvas@1.0.0-rc.5/dist/html2canvas.min.js"></script>
    {% if not object.youtube_id %}
        <script>
            $(document).ready(function(){
                var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

                function csrfSafeMethod(method) {
                    // these HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }

                $.ajaxSetup({
                    beforeSend: function (xhr, settings) {
                        // if not safe, set csrftoken
                        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                })

                $("#createBtn").click(function(){
                    $("#createBtn").attr('disabled', true);
                    $.post("{% url 'video_create_api' %}", {
                        'podcast': '{{object.podcast.id}}',
                        'episode': '{{object.id}}'
                    }).then(function(data, status, xhr){
                        console.log(status)
                        if (status === 'success') {
                            window.location.replace("{% url 'videosync_episode_upload' episode.podcast.slug episode.pk %}")
                        } else {
                            $('#errorMessage').show();
                            $("#createBtn").removeAttr('disabled');
                        }
                    }).catch(function(err, status, xhr){
                        $('#errorMessage').show();
                    });
                })

                $("#uploadBtn").click(function(){
                    $.post("{% url 'youtube_upload_api' %}", {
                        'podcast': '{{object.podcast.id}}',
                        'episode': '{{object.id}}'
                    }).then(function(data, status, xhr){
                        if (status === 'success') {
                            window.location.replace("{% url 'videosync_episode_list_page' episode.podcast.slug %}")
                        } else {
                            $('#errorMessage').show()
                        }
                    }).catch(function(err){
                        console.log(err)
                    })
                })

            })
        </script>
    {% endif %}
{% endblock %}